version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  groups:
    GitHub_Actions:
      patterns:
        - "*"  # Group all Actions updates into a single larger pull request
  schedule:
    interval: weekly
