# Generated by Django 3.0.4 on 2020-03-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialapp',
            name='cert',
            field=models.CharField(blank=True, help_text='.p8 file contents (if required)', max_length=500, verbose_name='Certificate'),
        ),
    ]
