# Generated by Django 3.0.8 on 2020-07-29 09:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTimeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='action')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created')),
                ('email_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress', verbose_name='e-mail address')),
            ],
        ),
    ]
