# Generated by Django 4.2.2 on 2023-06-14 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_alter_emailaddress_create_unique_verified_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaddress",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="email address"),
        ),
    ]
