# Generated by Django 3.2.20 on 2023-10-01 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_emailaddress_lower"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emailaddress",
            name="account_emailaddress_upper",
        ),
        migrations.AlterField(
            model_name="emailaddress",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="email address"
            ),
        ),
    ]
